# Project Cancer Detection

## Breast Cancer Wisconsin (Diagnostic) Data Set

In [9]:
import numpy as np
import pandas as pd

In [16]:
df = pd.read_csv('data.csv', header = 0)
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [18]:
df.pop('Unnamed: 32')

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
15    NaN
16    NaN
17    NaN
18    NaN
19    NaN
20    NaN
21    NaN
22    NaN
23    NaN
24    NaN
25    NaN
26    NaN
27    NaN
28    NaN
29    NaN
       ..
539   NaN
540   NaN
541   NaN
542   NaN
543   NaN
544   NaN
545   NaN
546   NaN
547   NaN
548   NaN
549   NaN
550   NaN
551   NaN
552   NaN
553   NaN
554   NaN
555   NaN
556   NaN
557   NaN
558   NaN
559   NaN
560   NaN
561   NaN
562   NaN
563   NaN
564   NaN
565   NaN
566   NaN
567   NaN
568   NaN
Name: Unnamed: 32, Length: 569, dtype: float64

In [19]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
id                         569 non-null int64
diagnosis                  569 non-null object
radius_mean                569 non-null float64
texture_mean               569 non-null float64
perimeter_mean             569 non-null float64
area_mean                  569 non-null float64
smoothness_mean            569 non-null float64
compactness_mean           569 non-null float64
concavity_mean             569 non-null float64
concave points_mean        569 non-null float64
symmetry_mean              569 non-null float64
fractal_dimension_mean     569 non-null float64
radius_se                  569 non-null float64
texture_se                 569 non-null float64
perimeter_se               569 non-null float64
area_se                    569 non-null float64
smoothness_se              569 non-null float64
compactness_se             569 non-null float64
concavity_se               569 non

In [21]:
df['diagnosis'].describe()

count     569
unique      2
top         B
freq      357
Name: diagnosis, dtype: object

In [22]:
df['diagnosis'].value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

For diagnosis B = Benign, M = Malignant, convert to 0,1

Benign = 0, Malignant = 1

In [24]:
diag_to_num = {'B' : 0,
              'M' : 1}
df['diagnosis'] = df['diagnosis'].map(diag_to_num)

In [25]:
df['diagnosis'].value_counts()

0    357
1    212
Name: diagnosis, dtype: int64

In [26]:
X = df.drop(['id', 'diagnosis'], axis=1)
X_col = X.columns

In [28]:
y = df['diagnosis']

## Pre-processing

In [29]:
from sklearn.preprocessing import StandardScaler

In [30]:
X = StandardScaler().fit_transform(X.values)

## Training

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
df1 = pd.DataFrame(X, columns = X_col)
df1.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0     1.097064     -2.073335        1.269934   0.984375         1.568466   
1     1.829821     -0.353632        1.685955   1.908708        -0.826962   
2     1.579888      0.456187        1.566503   1.558884         0.942210   
3    -0.768909      0.253732       -0.592687  -0.764464         3.283553   
4     1.750297     -1.151816        1.776573   1.826229         0.280372   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0          3.283515        2.652874             2.532475       2.217515   
1         -0.487072       -0.023846             0.548144       0.001392   
2          1.052926        1.363478             2.037231       0.939685   
3          3.402909        1.915897             1.451707       2.867383   
4          0.539340        1.371011             1.428493      -0.009560   

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                2.255747  ...      1.886690      -1.359293         2.303601   
1               -0.868652  ...      1.805927      -0.369203         1.535126   
2               -0.398008  ...      1.511870      -0.023974         1.347475   
3                4.910919  ...     -0.281464       0.133984        -0.249939   
4               -0.562450  ...      1.298575      -1.466770         1.338539   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0    2.001237          1.307686           2.616665         2.109526   
1    1.890489         -0.375612          -0.430444        -0.146749   
2    1.456285          0.527407           1.082932         0.854974   
3   -0.550021          3.394275           3.893397         1.989588   
4    1.220724          0.220556          -0.313395         0.613179   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0              2.296076        2.750622                 1.937015  
1              1.087084       -0.243890                 0.281190  
2              1.955000        1.152255                 0.201391  
3              2.175786        6.046041                 4.935010  
4              0.729259       -0.868353                -0.397100  

[5 rows x 30 columns]

In [34]:
X_train, X_test, y_train, y_test = train_test_split(df1, y, test_size = 0.2, random_state = 42)

In [35]:
from sklearn.preprocessing import MinMaxScaler
pd.DataFrame(MinMaxScaler().fit_transform(df.drop(['id','diagnosis'], axis = 1).values), columns=X_col).head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0     0.521037      0.022658        0.545989   0.363733         0.593753   
1     0.643144      0.272574        0.615783   0.501591         0.289880   
2     0.601496      0.390260        0.595743   0.449417         0.514309   
3     0.210090      0.360839        0.233501   0.102906         0.811321   
4     0.629893      0.156578        0.630986   0.489290         0.430351   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0          0.792037        0.703140             0.731113       0.686364   
1          0.181768        0.203608             0.348757       0.379798   
2          0.431017        0.462512             0.635686       0.509596   
3          0.811361        0.565604             0.522863       0.776263   
4          0.347893        0.463918             0.518390       0.378283   

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                0.605518  ...      0.620776       0.141525         0.668310   
1                0.141323  ...      0.606901       0.303571         0.539818   
2                0.211247  ...      0.556386       0.360075         0.508442   
3                1.000000  ...      0.248310       0.385928         0.241347   
4                0.186816  ...      0.519744       0.123934         0.506948   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0    0.450698          0.601136           0.619292         0.568610   
1    0.435214          0.347553           0.154563         0.192971   
2    0.374508          0.483590           0.385375         0.359744   
3    0.094008          0.915472           0.814012         0.548642   
4    0.341575          0.437364           0.172415         0.319489   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0              0.912027        0.598462                 0.418864  
1              0.639175        0.233590                 0.222878  
2              0.835052        0.403706                 0.213433  
3              0.884880        1.000000                 0.773711  
4              0.558419        0.157500                 0.142595  

[5 rows x 30 columns]

In [36]:
from sklearn.preprocessing import Normalizer
pd.DataFrame(Normalizer().fit_transform(df.drop(['id','diagnosis'], axis = 1).values), columns=X_col).head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0     0.007925      0.004573        0.054099   0.440986         0.000052   
1     0.008666      0.007486        0.055988   0.558619         0.000036   
2     0.009367      0.010109        0.061842   0.572276         0.000052   
3     0.016325      0.029133        0.110899   0.551922         0.000204   
4     0.009883      0.006985        0.065808   0.631774         0.000049   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0          0.000122        0.000132             0.000065       0.000107   
1          0.000033        0.000037             0.000030       0.000076   
2          0.000076        0.000094             0.000061       0.000098   
3          0.000406        0.000345             0.000150       0.000371   
4          0.000065        0.000096             0.000051       0.000088   

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                0.000035  ...      0.011181       0.007635         0.081325   
1                0.000024  ...      0.010528       0.009862         0.066899   
2                0.000029  ...      0.011212       0.012145         0.072545   
3                0.000139  ...      0.021314       0.037881         0.141333   
4                0.000029  ...      0.010979       0.008120         0.074137   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0    0.889462          0.000071           0.000293         0.000314   
1    0.824026          0.000052           0.000079         0.000102   
2    0.812984          0.000069           0.000202         0.000214   
3    0.811515          0.000300           0.001238         0.000982   
4    0.767189          0.000067           0.000100         0.000195   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0              0.000117        0.000203                 0.000052  
1              0.000078        0.000116                 0.000038  
2              0.000116        0.000172                 0.000042  
3              0.000368        0.000949                 0.000247  
4              0.000079        0.000115                 0.000037  

[5 rows x 30 columns]

In [37]:
from sklearn.neighbors import KNeighborsClassifier

In [38]:
knn = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')

In [39]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [40]:
from sklearn.model_selection import cross_val_predict, cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [41]:
def print_score(clf, X_train, X_test, y_train, y_test, train = True):
    '''
    print accuracy score and confusion matrix
    '''
    
    if train:
        '''
        train performance
        '''
        print('Train Result: \n')
        print('Accuracy Score: {0:.4f}\n'.format(accuracy_score(y_train, clf.predict(X_train))))
        print('Classification Report: \n {} \n'.format(classification_report(y_train, clf.predict(X_train))))
        print('Confusion Matrix: \n {} \n'.format(confusion_matrix(y_train, clf.predict(X_train))))
        
        res = cross_val_score(clf, X_train, y_train, cv = 10, scoring='accuracy')
        print('Average Accuracy: \t {0:.4f}'.format(np.mean(res)))
        print('Average SD: \t\t {0:.4f}'.format(np.std(res)))
        
    elif train == False:
        '''
        test performance
        '''
        print('Test Result \n')
        print('Accuracy Score: {0:.4f}\n'.format(accuracy_score(y_test, clf.predict(X_test))))
        print('Classification Report: \n {} \n'.format(classification_report(y_test, clf.predict(X_test))))
        print('Confusion Matrix: \n {} \n'.format(confusion_matrix(y_test, clf.predict(X_test))))

In [42]:
print_score(knn, X_train, X_test, y_train, y_test, train = True)

Train Result: 

Accuracy Score: 0.9802

Classification Report: 
               precision    recall  f1-score   support

           0       0.97      1.00      0.98       286
           1       1.00      0.95      0.97       169

   micro avg       0.98      0.98      0.98       455
   macro avg       0.98      0.97      0.98       455
weighted avg       0.98      0.98      0.98       455
 

Confusion Matrix: 
 [[286   0]
 [  9 160]] 

Average Accuracy: 	 0.9668
Average SD: 		 0.0271


In [43]:
print_score(knn, X_train, X_test, y_train, y_test, train = False)

Test Result 

Accuracy Score: 0.9474

Classification Report: 
               precision    recall  f1-score   support

           0       0.96      0.96      0.96        71
           1       0.93      0.93      0.93        43

   micro avg       0.95      0.95      0.95       114
   macro avg       0.94      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114
 

Confusion Matrix: 
 [[68  3]
 [ 3 40]] 



# Grid Search

In [44]:
from sklearn.model_selection import GridSearchCV

In [45]:
knn.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [50]:
params = {'n_neighbors' : [1,2,3,4,5,6,7,8,9,10],
         'metric' : ['euclidean', 'manhattan', 'chebyshev']}

In [51]:
grid_search_cv = GridSearchCV(KNeighborsClassifier(),
                             params,
                             n_jobs=-1,
                             verbose=1)

In [52]:
grid_search_cv.fit(X_train,y_train)

C:\Users\Drake\Anaconda3\envs\Iris_2\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


Fitting 3 folds for each of 30 candidates, totalling 90 fits


[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    1.9s
[Parallel(n_jobs=-1)]: Done  90 out of  90 | elapsed:    2.2s finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'metric': ['euclidean', 'manhattan', 'chebyshev']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=1)

In [53]:
grid_search_cv.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [54]:
grid_search_cv.best_params_

{'metric': 'euclidean', 'n_neighbors': 5}

In [55]:
grid_search_cv.cv_results_['mean_train_score']

C:\Users\Drake\Anaconda3\envs\Iris_2\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)


array([1.        , 0.97582636, 0.9868058 , 0.97032212, 0.97801934,
       0.9659289 , 0.97032212, 0.96263942, 0.96814366, 0.96263942,
       1.        , 0.98022685, 0.98900604, 0.97362612, 0.97362612,
       0.96812914, 0.97142587, 0.96483967, 0.96703991, 0.96264668,
       1.        , 0.96921837, 0.97690833, 0.96263942, 0.96481788,
       0.95605321, 0.9626249 , 0.95054897, 0.95054171, 0.94066603])

In [56]:
grid_search_cv.cv_results_

C:\Users\Drake\Anaconda3\envs\Iris_2\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\Drake\Anaconda3\envs\Iris_2\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\Drake\Anaconda3\envs\Iris_2\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split2_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\Drake\Anac

{'mean_fit_time': array([0.00266695, 0.00300034, 0.00266695, 0.00233332, 0.00233348,
        0.0023334 , 0.00266671, 0.0023334 , 0.00200009, 0.00233348,
        0.00266695, 0.0023334 , 0.00233356, 0.00266695, 0.00166678,
        0.00233356, 0.00300034, 0.00200025, 0.00233356, 0.0023334 ,
        0.0023334 , 0.00233364, 0.00233332, 0.00233364, 0.0023334 ,
        0.00200009, 0.00166678, 0.00166663, 0.0016667 , 0.00100009]),
 'std_fit_time': array([4.71370354e-04, 8.16437410e-04, 4.71370354e-04, 4.71426560e-04,
        4.71314168e-04, 4.71370354e-04, 4.71370354e-04, 4.71370394e-04,
        0.00000000e+00, 4.71482745e-04, 4.71370354e-04, 4.71370354e-04,
        4.71257962e-04, 4.71370394e-04, 4.71201776e-04, 4.71426560e-04,
        1.41439204e-03, 1.12391596e-07, 4.71426560e-04, 4.71370354e-04,
        4.71370354e-04, 4.71538951e-04, 4.71426560e-04, 4.71370354e-04,
        4.71370354e-04, 0.00000000e+00, 4.71538951e-04, 4.71426560e-04,
        4.71482745e-04, 2.24783192e-07]),
 'mean_scor

## Comparing w/ Other Models

In [58]:
from sklearn.ensemble import RandomForestClassifier

In [59]:
rf_clf = RandomForestClassifier()
rf_clf.fit(X_train, y_train.ravel())

C:\Users\Drake\Anaconda3\envs\Iris_2\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [60]:
print_score(rf_clf, X_train, X_test, y_train.ravel(), y_test, train = True)

Train Result: 

Accuracy Score: 0.9956

Classification Report: 
               precision    recall  f1-score   support

           0       0.99      1.00      1.00       286
           1       1.00      0.99      0.99       169

   micro avg       1.00      1.00      1.00       455
   macro avg       1.00      0.99      1.00       455
weighted avg       1.00      1.00      1.00       455
 

Confusion Matrix: 
 [[286   0]
 [  2 167]] 

Average Accuracy: 	 0.9537
Average SD: 		 0.0289


In [61]:
print_score(rf_clf, X_train, X_test, y_train, y_test, train = False)

Test Result 

Accuracy Score: 0.9561

Classification Report: 
               precision    recall  f1-score   support

           0       0.95      0.99      0.97        71
           1       0.97      0.91      0.94        43

   micro avg       0.96      0.96      0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114
 

Confusion Matrix: 
 [[70  1]
 [ 4 39]] 



In [62]:
import xgboost as xgb

In [63]:
xgb_clf = xgb.XGBClassifier(max_depth = 3, n_estimators = 5000, learning_rate = 0.2)

In [64]:
xgb_clf.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=0.2,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=5000, n_jobs=1, nthread=None,
       objective='binary:logistic', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1)

In [65]:
print_score(xgb_clf, X_train, X_test, y_train, y_test, train = True)

Train Result: 

Accuracy Score: 1.0000

Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       286
           1       1.00      1.00      1.00       169

   micro avg       1.00      1.00      1.00       455
   macro avg       1.00      1.00      1.00       455
weighted avg       1.00      1.00      1.00       455
 

Confusion Matrix: 
 [[286   0]
 [  0 169]] 

Average Accuracy: 	 0.9670
Average SD: 		 0.0224


In [66]:
print_score(xgb_clf, X_train, X_test, y_train, y_test, train = False)

Test Result 

Accuracy Score: 0.9649

Classification Report: 
               precision    recall  f1-score   support

           0       0.96      0.99      0.97        71
           1       0.98      0.93      0.95        43

   micro avg       0.96      0.96      0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114
 

Confusion Matrix: 
 [[70  1]
 [ 3 40]] 

